[0m17:46:14.705225 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D17EB7F220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D100FE4640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D100FE4820>]}


============================== 17:46:14.705225 | fb5471d7-ea54-4ee7-990c-1346b6880cf3 ==============================
[0m17:46:14.705225 [info ] [MainThread]: Running with dbt=1.8.4
[0m17:46:14.705225 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\FinnCharlton\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:46:14.716190 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\FinnCharlton\Github Repos\TableauServerOverview\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:46:14.726600 [debug] [MainThread]: Command `dbt run` failed at 17:46:14.726600 after 0.10 seconds
[0m17:46:14.727715 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D17EB7F220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D100FE46A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D100FE45B0>]}
[0m17:46:14.727715 [debug] [MainThread]: Flushing usage events
[0m12:03:36.403801 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C9E9B7F160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C9EC0E4550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C9EC0E4730>]}


============================== 12:03:36.408871 | 2d56ab2e-86ab-4971-b487-898d3af01fd8 ==============================
[0m12:03:36.408871 [info ] [MainThread]: Running with dbt=1.8.4
[0m12:03:36.409395 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\FinnCharlton\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt build', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m12:03:36.410432 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\FinnCharlton\Github Repos\TableauServerOverview\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:03:36.412427 [debug] [MainThread]: Command `dbt build` failed at 12:03:36.412427 after 0.09 seconds
[0m12:03:36.413413 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C9E9B7F160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C9EC0E45B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C9EC0E44C0>]}
[0m12:03:36.413413 [debug] [MainThread]: Flushing usage events
[0m14:27:26.740801 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019929786BF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001992BDF3AF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001992BDF3910>]}


============================== 14:27:26.763533 | 39e2ec01-0052-47a4-b7b2-992529da3cd9 ==============================
[0m14:27:26.763533 [info ] [MainThread]: Running with dbt=1.8.4
[0m14:27:26.764543 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\FinnCharlton\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt build', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:27:26.764543 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\FinnCharlton\Github Repos\TableauServerOverview\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:27:26.766575 [debug] [MainThread]: Command `dbt build` failed at 14:27:26.766575 after 0.12 seconds
[0m14:27:26.766575 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019929786BF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001992BDF3A90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001992BDF3B80>]}
[0m14:27:26.767601 [debug] [MainThread]: Flushing usage events
